name: Build and Push s

on:
  push:
    branches:
      - master

jobs:
  push-image:
    runs-on: ubuntu-latest

    env:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Push s Image
        run: make push
